apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: soc-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://socuser:socpass123@postgres-service:5432/soc_db"
  FLASK_SECRET: "super-secret-key-change-me"
  DB_PASSWORD: "socpass123"
